1. Create a 1D NumPy array of numbers from 1 to 20 and reshape it into a 4x5 matrix. 

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18,19,20])

newarr = arr.reshape(4,5)

print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2. From a given array [10, 15, 20, 25, 30, 35], extract all values greater than 20. 

In [7]:
import numpy as np

arr = np.array([10,15,20,25,30,35])
for i in arr:
    if i>=20:
        print("greater then 20",i)

greater then 20 20
greater then 20 25
greater then 20 30
greater then 20 35


3. Given two arrays: 
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
Perform element-wise addition, subtraction, multiplication, and division.

In [13]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print("addition",np.add(a,b))
print("subtraction",np.subtract(a,b))
print("multiplication",np.multiply(a,b))
print("division",np.divide(a,b))

addition [5 7 9]
subtraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


4. Replace all odd numbers in the array below with -1 

In [24]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a[a % 2 != 0] = -1
print("arr=",a)
    

arr= [-1  2 -1  4 -1  6]


5. Reverse the following array using slicing

In [25]:
import numpy as np
a=np.array([1,2,3,4,5])
rev=a[::-1]
print(rev)


[5 4 3 2 1]


6. Create a 4x4 matrix of numbers from 1 to 16. Extract the main diagonal elements. 

In [27]:
import numpy as np
a = np.arange(1, 17).reshape(4, 4)
print("Matrix:\n", a)
diag = np.diagonal(a)
print("Main diagonal:", diag)



Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Main diagonal: [ 1  6 11 16]


7. Find the unique elements and their counts in the array: 

In [30]:
import numpy as np
a=np.array([1,2,2,3,3,3,4,4,4,4,4,5])
unique, counts = np.unique(a, return_counts=True)

print("Unique elements:", unique)
print("Counts:", counts)


Unique elements: [1 2 3 4 5]
Counts: [1 2 3 5 1]


8. Replace all values greater than 50 with 0 in this array 

In [32]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print(a)
a[a > 50] = 0
print("After replacement:", a)


[10 20 30 40 50 60 70 80]
After replacement: [10 20 30 40 50  0  0  0]


9. Find the index of the maximum value in the array 

In [46]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a1= np.argmax(a)
print("max=",a1)

max= 6


10. Given a 3x3 matrix, find the sum of each row and each column 

In [48]:
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
row_sum = np.sum(a, axis=1)
print("Sum of each row:", row_sum)
col_sum = np.sum(a, axis=0)
print("Sum of each column:", col_sum)




Sum of each row: [ 6 15 24]
Sum of each column: [12 15 18]


11. Use NumPy to reshape the array below into a 2D array with 3 rows (use -1 for 
automatic column count) 

In [43]:
a = np.array([1, 2, 3,4, 5, 6,7, 8, 9])
b=a.reshape(3,-1)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


12. Count how many values are divisible by 3 in this array 

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.count_nonzero(a%3==0)
print(b)
    

3


13. Sort each row of the following 2D array 

In [47]:
a=np.array([[1,3,2],[6,4,5],[8,9,7]])
b=np.sort(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
